🎨 Design: 변경 nav하단 바 css
OZ-Coding-School/oz_03_collabo-001-FE pull request #43
Opened 2024-08-20 07:41 UTC by doin-N

## 개요
기존 테일윈드에서 스타일로 변경

## Issue 유형
Fixes: #5

## PR 유형

어떤 변경 사항이 있나요?

- [ ] 새로운 기능 추가
- [ ] 버그 수정
- [x] CSS 등 사용자 UI 디자인 변경
- [ ] 코드 포맷팅, 코드 수정이 없음
- [ ] 코드 리팩토링
- [ ] 필요한 주석 추가 및 변경
- [ ] 문서 파일 추가 및 수정
- [ ] 테스트 코드, 리팩토링 테스트 코드 추가
- [ ] 빌드 업무 수정, 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정 또는 이동
- [ ] 파일 또는 코드 삭제

## PR Checklist

PR이 다음 요구 사항을 충족하는지 확인하세요.

- [x] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [x] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).

2024-08-20 09:01 UTC, Supernova-428 approved these changes

2024-08-20 09:27 UTC, Yi-HyeonJu requested changes

2024-08-20 09:27 UTC, Yi-HyeonJu commented on src/components/BDPlace/PlaceTopNav.tsx
> +            style={{
클래스 네임을 조건부로 줘야할 때 테일윈드 머지쓰면 가독성이 조아져요! 한번 써서 다시 풀리퀘 해주세요~!
https://github.com/dcastil/tailwind-merge

2024-08-21 02:01 UTC, doin-N commented on src/components/BDPlace/PlaceTopNav.tsx
> +            style={{
yep 👍  수정 후 다시 요청하겠슴다

2024-08-21 02:12 UTC, closed without merging